CadastroCarros/Models/Carro.cs
using System.ComponentModel.DataAnnotations;

namespace CadastroCarros.Models
{
    public class Carro
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatorio")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres")]
        public string Marca { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatorio")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres")]
        public string Modelo { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatorio")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "O campo {0} precisa ter entre {2} e {1} caracteres")]
        public string Cor { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatorio")]
        [DataType(DataType.DateTime, ErrorMessage = "O campo {0} está em formato incorreto")]
        [Display(Name = "Data de Fabricação")]
        public DateTime dataFabricacao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatorio")]
        [DataType(DataType.DateTime, ErrorMessage = "O campo {0} está em formato incorreto")]
        [Display(Name = "Ano de Fabricação")]
        public int anoFabricacao {  get; set; }


        public bool Vendido { get; set; }
         
    }
}

CadastroCarros/Models/ErrorViewModel.cs
namespace CadastroCarros.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroCarros/Controllers/CarrosController.cs
using CadastroCarros.Data;
using CadastroCarros.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CadastroCarros.Controllers
{
    public class CarrosController : Controller
    {
        private readonly AppDbContext _context;

        public CarrosController(AppDbContext context)
        {
            _context = context;
        }

        //Exibindo todos os resultados
        public async Task<IActionResult> Index()
        {
            var carros = await _context.Carro.ToListAsync();
            return View(carros);
        }

        // GET:Carros/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if ( _context.Carro == null )
            {
                return NotFound();
            }

            var carro = await _context.Carro.FirstOrDefaultAsync();

            if ( carro == null )
            {
                return NotFound();
            }

            return View(carro);
        }

        [Route("novo")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("novo")]
        public async Task<IActionResult> Create([Bind("Id,Marca,Modelo,Cor,dataFabricacao,anoFabricacao,Vendido")]Carro carro)
        {
            if( ModelState.IsValid )
            {
                _context.Add(carro);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(carro);
        }

        [Route("editar/{id:int}")]
        // GET: Carros/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if( _context.Carro == null )
            {
                return NotFound();
            }
            var carro = await _context.Carro.FindAsync(id);
            if( carro == null )
            {
                return NotFound();
            }
            return View(carro);
        }

        [HttpPost("editar/{id:int}")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Marca,Modelo,Cor,dataFabricacao,anoFabricacao,Vendido")]Carro carro) 
        { 
            if( id != carro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid )
            {
                try
                {
                    _context.Update(carro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarroExists(carro.Id))
                    {
                        return NotFound();
                    }
                    else throw;
                }
                return RedirectToAction(nameof(Index));
            }
                return View(carro);
        }

        [Route("excluir/{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Carro == null)
            {
                return NotFound();
            }

            var carro = await _context.Carro.FirstOrDefaultAsync(c => c.Id == id);
            if ( carro == null)
            {
                return NotFound();
            }
            return View(carro);
        }

        [HttpPost("excluir/{id:int}"), ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carro = await _context.Carro.FindAsync(id);
            if ( carro != null )
            {
                _context.Carro.Remove(carro);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarroExists(int id)
        {
            return _context.Carro.Any(e => e.Id == id);
        }
    }
}

CadastroCarros/Controllers/HomeController.cs
using CadastroCarros.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CadastroCarros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroCarros/Views/Carros/Create.cshtml
@model CadastroCarros.Models.Carro

@{
    ViewData["Title"] = "Criar novo cadastro de Carro";
}
<h1> @ViewData["Title"]</h1>
<h4>Preencha os dados corretamente</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cor" class="control-label"></label>
                <input asp-for="Cor" class="form-control" />
                <span asp-validation-for="Cor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="dataFabricacao" class="control-label"></label>
                <input asp-for="dataFabricacao" class="form-control" />
                <span asp-validation-for="dataFabricacao" class="text-danger"></span>
            </div>

@*             <div class="form-group">
                <label asp-for="anoFabricacao" class="control-label"></label>
                <input asp-for="anoFabricacao" class="form-control" />
                <span asp-validation-for="anoFabricacao" class="text-danger"></span>
            </div> *@

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Vendido" /> @Html.DisplayNameFor(model => model.Vendido)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" /> |
                <a asp-action="Index" class="btn btn-warning">Voltar</a>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}


                    @* Parei aqui, continuar *@

CadastroCarros/Views/Carros/Delete.cshtml
@model CadastroCarros.Models.Carro

@{
    ViewData["Title"] = "Excluir Carro";
}

<h1>@ViewData["Title"]</h1>

<h3>Tem certeza que deseja excluir este veiculo de Marca: @Model.Marca, Modelo: @Model.Modelo e Cor: @Model.Cor?</h3>
<hr />

<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
            <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
           <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dataFabricacao)
        </dt>
        <dd class="col-sm-10">
            @Model.dataFabricacao.ToString("dd/MM/yyyy")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vendido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vendido)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-warning">Voltar</a>
    </form>
</div>

CadastroCarros/Views/Carros/Details.cshtml
@model CadastroCarros.Models.Carro

@{
    ViewData["Title"] = "Detalhes do Carro";
}

<h1>@ViewData["Title"]</h1>

<div>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.dataFabricacao)
        </dt>
        <dd class="col-sm-10">
            @Model.dataFabricacao.ToString("dd/MM/yyyy")

        </dd>
@*         <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Avaliacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Avaliacao)
        </dd> *@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Vendido)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Vendido)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model?.Id" /> Editar</a> |
    <a asp-action="Index" class="btn btn-warning">Voltar</a>
</div>



      

CadastroCarros/Views/Carros/Edit.cshtml
@model CadastroCarros.Models.Carro

@{
    ViewData["Title"] = "Editar cadastro de Carro";
}
<h1> @ViewData["Title"]</h1>
<h4> Dados do Carro @Model.Modelo</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Cor" class="control-label"></label>
                <input asp-for="Cor" class="form-control" />
                <span asp-validation-for="Cor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="dataFabricacao" class="control-label"></label>
                <input asp-for="dataFabricacao" class="form-control" />
                <span asp-validation-for="dataFabricacao" class="text-danger"></span>
            </div>

            @*             <div class="form-group">
            <label asp-for="anoFabricacao" class="control-label"></label>
            <input asp-for="anoFabricacao" class="form-control" />
            <span asp-validation-for="anoFabricacao" class="text-danger"></span>
            </div> *@

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Vendido" /> @Html.DisplayNameFor(model => model.Vendido)
                </label>
            </div>

            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" /> |
                <a asp-action="Index" class="btn btn-warning">Voltar</a>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}


@* Parei aqui, continuar *@

CadastroCarros/Views/Carros/Index.cshtml
@model IEnumerable<CadastroCarros.Models.Carro>

@{
    ViewData["Title"] = "Lista de Carros Cadastrados";
}
<h1> @ViewData["Title"]</h1> 

<p>
    <a class="btn btn-primary" asp-action="Create"><span class="fa fa-plus"></span>Novo</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dataFabricacao)  
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vendido)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach( var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cor)
                </td>
                <td>
                    @item.dataFabricacao.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Vendido)
                </td>
                <td>
                    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Excluir</a>

                </td>
            </tr>
        }
    </tbody>
</table>

CadastroCarros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CadastroCarros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadastroCarros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadastroCarros.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CadastroCarros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carros" asp-action="Index">Carros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CadastroCarros - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>